# Robustness Checks Notebook

This notebook validates whether conclusions remain stable under alternative specifications and samples.

Checks:
- Ramsey RESET on forecast calibration regressions.
- Validation-vs-test error stability tests.
- Tail-event exclusion sensitivity for DM tests.

In [13]:
import os
import sys
import numpy as np
import pandas as pd
from scipy import stats

if os.path.basename(os.getcwd()) == 'khanh_model_analysis':
    os.chdir('..')

sys.path.append('src')

from statistical_validation import (
    set_reproducible_seed,
    load_config,
    discover_forecasts,
    reset_specification_test,
    run_dm_comparisons,
    build_default_dm_pairs,
)

set_reproducible_seed(42)
pd.set_option('display.max_rows', 300)
pd.set_option('display.max_columns', 200)

#### Interpretation
This setup cell prepares robustness utilities. Its role is to ensure all follow-up tests are run under the same package versions and helper definitions.

In [14]:
config = load_config('configs/pipeline_config.yaml')
active_target = config['active_target']
forecasts = discover_forecasts(config)

print(f'Active target: {active_target}')
print('Rows:', len(forecasts))
print('Models:', sorted(forecasts['Model'].unique().tolist()))

Active target: PHP
Rows: 63450
Models: ['arima', 'arimax', 'baseline_ar1', 'baseline_mean', 'baseline_rw', 'hybrid_arima_mlp', 'hybrid_arima_svr', 'hybrid_arimax_mlp', 'hybrid_arimax_svr', 'hybrid_var_mlp', 'hybrid_var_svr', 'hybrid_varx_mlp', 'hybrid_varx_svr', 'var', 'varx']

#### Interpretation
The printed metadata verifies active target, sample size, and model count. These checks protect robustness conclusions from accidental data-path mismatch.

### Why robustness matters

A model can look strong on one split and still fail under small specification changes. The checks below ask whether conclusions survive a RESET test, whether validation errors behave similarly on the test set, and whether DM conclusions are driven by a few extreme tail observations. That is the right standard for a forecasting pipeline that may later expand to ARIMAX, VARX, or new hybrid variants.

## 1) Ramsey RESET (Specification Bias)

Null: no omitted non-linear terms in calibration equation `Actual ~ Forecast`.

In [15]:
reset_val = reset_specification_test(forecasts, set_name='val')
reset_test = reset_specification_test(forecasts, set_name='test')

display(reset_val.sort_values(['Pair', 'RESET_pvalue']))
display(reset_test.sort_values(['Pair', 'RESET_pvalue']))

reset_compare = reset_val.merge(
    reset_test,
    on=['Pair', 'Model'],
    suffixes=('_val', '_test'),
)
reset_compare['stable_conclusion'] = (
    reset_compare['Specification_bias_5pct_val'] == reset_compare['Specification_bias_5pct_test']
)
display(reset_compare[['Pair', 'Model', 'RESET_pvalue_val', 'RESET_pvalue_test', 'stable_conclusion']])

,Pair,Model,Set,R2,RESET_F,RESET_pvalue,Specification_bias_5pct,RESET_note
5,CNYPHP_RET,hybrid_arima_mlp,val,0.088081,22.879028,0.000002,True,OK
6,CNYPHP_RET,hybrid_arima_svr,val,0.017301,21.269198,0.000005,True,OK
7,CNYPHP_RET,hybrid_arimax_mlp,val,0.104905,19.214939,0.000015,True,OK
8,CNYPHP_RET,hybrid_arimax_svr,val,0.040494,19.060807,0.000016,True,OK
0,CNYPHP_RET,arima,val,0.099395,9.426465,0.002278,True,OK
1,CNYPHP_RET,arimax,val,0.112306,9.256289,0.002494,True,OK
2,CNYPHP_RET,baseline_ar1,val,0.082906,7.960822,0.005007,True,OK
14,CNYPHP_RET,varx,val,0.011156,4.413658,0.036248,True,OK
13,CNYPHP_RET,var,val,0.003700,2.973281,0.085386,False,OK
10,CNYPHP_RET,hybrid_var_svr,val,0.001677,1.693737,0.193822,False,OK
9,CNYPHP_RET,hybrid_var_mlp,val,0.007336,0.189341,0.663689,False,OK
12,CNYPHP_RET,hybrid_varx_svr,val,0.001241,0.098431,0.753877,False,OK
11,CNYPHP_RET,hybrid_varx_mlp,val,0.015468,0.090155,0.764128,False,OK
3,CNYPHP_RET,baseline_mean,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
4,CNYPHP_RET,baseline_rw,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
28,HKDPHP_RET,var,val,0.008635,4.765699,0.029585,True,OK
22,HKDPHP_RET,hybrid_arimax_mlp,val,0.060668,3.775148,0.052687,False,OK
29,HKDPHP_RET,varx,val,0.052250,3.268969,0.071317,False,OK
17,HKDPHP_RET,baseline_ar1,val,0.002983,2.413992,0.121009,False,OK
23,HKDPHP_RET,hybrid_arimax_svr,val,0.059329,1.242965,0.265538,False,OK
24,HKDPHP_RET,hybrid_var_mlp,val,0.006850,1.101126,0.294622,False,OK
15,HKDPHP_RET,arima,val,0.009144,0.655852,0.418487,False,OK
27,HKDPHP_RET,hybrid_varx_svr,val,0.053212,0.478047,0.489690,False,OK
16,HKDPHP_RET,arimax,val,0.063953,0.388825,0.533256,False,OK
20,HKDPHP_RET,hybrid_arima_mlp,val,0.004395,0.325468,0.568645,False,OK
21,HKDPHP_RET,hybrid_arima_svr,val,0.001220,0.200049,0.654912,False,OK
25,HKDPHP_RET,hybrid_var_svr,val,0.004152,0.016514,0.897809,False,OK
26,HKDPHP_RET,hybrid_varx_mlp,val,0.049581,0.000285,0.986530,False,OK
18,HKDPHP_RET,baseline_mean,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
19,HKDPHP_RET,baseline_rw,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
37,JPYPHP_RET,hybrid_arimax_mlp,val,0.066665,6.463687,0.011368,True,OK
35,JPYPHP_RET,hybrid_arima_mlp,val,0.008566,4.743522,0.029964,True,OK
38,JPYPHP_RET,hybrid_arimax_svr,val,0.076302,3.741663,0.053743,False,OK
31,JPYPHP_RET,arimax,val,0.063644,2.646865,0.104504,False,OK
32,JPYPHP_RET,baseline_ar1,val,0.004331,1.910341,0.167660,False,OK
30,JPYPHP_RET,arima,val,0.006536,1.754354,0.186051,False,OK
42,JPYPHP_RET,hybrid_varx_svr,val,0.031932,1.418704,0.234290,False,OK
39,JPYPHP_RET,hybrid_var_mlp,val,0.000353,1.385001,0.239918,False,OK
41,JPYPHP_RET,hybrid_varx_mlp,val,0.028278,1.133125,0.287721,False,OK
36,JPYPHP_RET,hybrid_arima_svr,val,0.009308,0.970784,0.325052,False,OK
44,JPYPHP_RET,varx,val,0.023815,0.631037,0.427424,False,OK
43,JPYPHP_RET,var,val,0.000020,0.152400,0.696450,False,OK
40,JPYPHP_RET,hybrid_var_svr,val,0.000010,0.125739,0.723069,False,OK
33,JPYPHP_RET,baseline_mean,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
34,JPYPHP_RET,baseline_rw,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
55,SGDPHP_RET,hybrid_var_svr,val,0.015680,16.867636,0.000048,True,OK
57,SGDPHP_RET,hybrid_varx_svr,val,0.039214,14.644272,0.000150,True,OK
47,SGDPHP_RET,baseline_ar1,val,0.025155,11.767725,0.000662,True,OK
45,SGDPHP_RET,arima,val,0.038831,8.274551,0.004225,True,OK
54,SGDPHP_RET,hybrid_var_mlp,val,0.006883,6.282669,0.012569,True,OK
53,SGDPHP_RET,hybrid_arimax_svr,val,0.102354,5.547586,0.018965,True,OK
50,SGDPHP_RET,hybrid_arima_mlp,val,0.058183,5.390258,0.020727,True,OK
51,SGDPHP_RET,hybrid_arima_svr,val,0.072181,5.117253,0.024199,True,OK
52,SGDPHP_RET,hybrid_arimax_mlp,val,0.076342,3.494952,0.062252,False,OK
46,SGDPHP_RET,arimax,val,0.062903,2.692655,0.101560,False,OK
58,SGDPHP_RET,var,val,0.002275,2.121134,0.146026,False,OK
56,SGDPHP_RET,hybrid_varx_mlp,val,0.023284,1.141129,0.286028,False,OK
59,SGDPHP_RET,varx,val,0.014637,0.117656,0.731762,False,OK
48,SGDPHP_RET,baseline_mean,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
49,SGDPHP_RET,baseline_rw,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
73,USDPHP_RET,var,val,0.007700,6.193654,0.013207,True,OK
67,USDPHP_RET,hybrid_arimax_mlp,val,0.067571,4.502206,0.034436,True,OK
74,USDPHP_RET,varx,val,0.056223,3.445493,0.064125,False,OK
68,USDPHP_RET,hybrid_arimax_svr,val,0.069607,3.212999,0.073775,False,OK
62,USDPHP_RET,baseline_ar1,val,0.002835,2.675975,0.102622,False,OK
69,USDPHP_RET,hybrid_var_mlp,val,0.005595,1.388141,0.239386,False,OK
70,USDPHP_RET,hybrid_var_svr,val,0.003229,1.174533,0.279094,False,OK
60,USDPHP_RET,arima,val,0.008748,0.685379,0.408211,False,OK
72,USDPHP_RET,hybrid_varx_svr,val,0.055734,0.672341,0.412702,False,OK
65,USDPHP_RET,hybrid_arima_mlp,val,0.003241,0.242942,0.622347,False,OK
61,USDPHP_RET,arimax,val,0.071349,0.100475,0.751417,False,OK
66,USDPHP_RET,hybrid_arima_svr,val,0.000698,0.074735,0.784698,False,OK
71,USDPHP_RET,hybrid_varx_mlp,val,0.053462,0.008641,0.925980,False,OK
63,USDPHP_RET,baseline_mean,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
64,USDPHP_RET,baseline_rw,val,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."

,Pair,Model,Set,R2,RESET_F,RESET_pvalue,Specification_bias_5pct,RESET_note
14,CNYPHP_RET,varx,test,0.169698,59.904960,7.494021e-14,True,OK
13,CNYPHP_RET,var,test,0.128851,55.403649,5.604828e-13,True,OK
1,CNYPHP_RET,arimax,test,0.198448,46.016788,3.998417e-11,True,OK
2,CNYPHP_RET,baseline_ar1,test,0.114140,43.764347,1.130262e-10,True,OK
0,CNYPHP_RET,arima,test,0.148077,39.980309,6.567532e-10,True,OK
9,CNYPHP_RET,hybrid_var_mlp,test,0.207689,21.214998,5.450566e-06,True,OK
11,CNYPHP_RET,hybrid_varx_mlp,test,0.252342,18.149940,2.522287e-05,True,OK
10,CNYPHP_RET,hybrid_var_svr,test,0.186407,10.166515,1.537193e-03,True,OK
5,CNYPHP_RET,hybrid_arima_mlp,test,0.237579,4.349233,3.762875e-02,True,OK
7,CNYPHP_RET,hybrid_arimax_mlp,test,0.287697,3.573162,5.940860e-02,False,OK
12,CNYPHP_RET,hybrid_varx_svr,test,0.246401,3.445687,6.411716e-02,False,OK
8,CNYPHP_RET,hybrid_arimax_svr,test,0.255792,0.395594,5.297155e-01,False,OK
6,CNYPHP_RET,hybrid_arima_svr,test,0.204722,0.134507,7.139883e-01,False,OK
3,CNYPHP_RET,baseline_mean,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
4,CNYPHP_RET,baseline_rw,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
28,HKDPHP_RET,var,test,0.147378,53.119061,1.569226e-12,True,OK
29,HKDPHP_RET,varx,test,0.208583,51.265864,3.632553e-12,True,OK
17,HKDPHP_RET,baseline_ar1,test,0.125011,50.317648,5.589486e-12,True,OK
15,HKDPHP_RET,arima,test,0.152734,48.109092,1.531152e-11,True,OK
16,HKDPHP_RET,arimax,test,0.239773,46.157979,3.747028e-11,True,OK
24,HKDPHP_RET,hybrid_var_mlp,test,0.249719,23.786324,1.530119e-06,True,OK
26,HKDPHP_RET,hybrid_varx_mlp,test,0.316970,16.730284,5.165986e-05,True,OK
22,HKDPHP_RET,hybrid_arimax_mlp,test,0.338835,10.070648,1.617263e-03,True,OK
25,HKDPHP_RET,hybrid_var_svr,test,0.267329,8.865959,3.073597e-03,True,OK
20,HKDPHP_RET,hybrid_arima_mlp,test,0.270409,8.329874,4.100989e-03,True,OK
27,HKDPHP_RET,hybrid_varx_svr,test,0.327657,5.046270,2.519791e-02,True,OK
21,HKDPHP_RET,hybrid_arima_svr,test,0.278604,3.746489,5.358939e-02,False,OK
23,HKDPHP_RET,hybrid_arimax_svr,test,0.349344,3.163975,7.600291e-02,False,OK
18,HKDPHP_RET,baseline_mean,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
19,HKDPHP_RET,baseline_rw,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
39,JPYPHP_RET,hybrid_var_mlp,test,0.087933,23.335207,1.910397e-06,True,OK
43,JPYPHP_RET,var,test,0.065861,18.900873,1.729615e-05,True,OK
32,JPYPHP_RET,baseline_ar1,test,0.098208,18.790307,1.828262e-05,True,OK
30,JPYPHP_RET,arima,test,0.104288,16.300772,6.423771e-05,True,OK
40,JPYPHP_RET,hybrid_var_svr,test,0.092052,9.363557,2.355329e-03,True,OK
42,JPYPHP_RET,hybrid_varx_svr,test,0.202929,8.830875,3.131989e-03,True,OK
41,JPYPHP_RET,hybrid_varx_mlp,test,0.189317,5.215297,2.288753e-02,True,OK
35,JPYPHP_RET,hybrid_arima_mlp,test,0.132579,4.354116,3.752217e-02,True,OK
44,JPYPHP_RET,varx,test,0.158734,2.754579,9.772277e-02,False,OK
38,JPYPHP_RET,hybrid_arimax_svr,test,0.214755,2.356194,1.255393e-01,False,OK
37,JPYPHP_RET,hybrid_arimax_mlp,test,0.196169,1.095776,2.957971e-01,False,OK
36,JPYPHP_RET,hybrid_arima_svr,test,0.109841,0.829128,3.630470e-01,False,OK
31,JPYPHP_RET,arimax,test,0.159617,0.240660,6.239860e-01,False,OK
33,JPYPHP_RET,baseline_mean,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
34,JPYPHP_RET,baseline_rw,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
47,SGDPHP_RET,baseline_ar1,test,0.158225,59.598058,8.590131e-14,True,OK
58,SGDPHP_RET,var,test,0.135022,51.265085,3.633838e-12,True,OK
45,SGDPHP_RET,arima,test,0.207560,50.766904,4.556616e-12,True,OK
46,SGDPHP_RET,arimax,test,0.216560,47.934745,1.658329e-11,True,OK
59,SGDPHP_RET,varx,test,0.150495,47.853372,1.721270e-11,True,OK
56,SGDPHP_RET,hybrid_varx_mlp,test,0.242834,33.864088,1.173912e-08,True,OK
54,SGDPHP_RET,hybrid_var_mlp,test,0.221177,33.495115,1.399227e-08,True,OK
55,SGDPHP_RET,hybrid_var_svr,test,0.241399,22.984914,2.270338e-06,True,OK
57,SGDPHP_RET,hybrid_varx_svr,test,0.259777,21.186005,5.529613e-06,True,OK
52,SGDPHP_RET,hybrid_arimax_mlp,test,0.307032,15.273549,1.083926e-04,True,OK
50,SGDPHP_RET,hybrid_arima_mlp,test,0.288764,10.399385,1.359068e-03,True,OK
53,SGDPHP_RET,hybrid_arimax_svr,test,0.297853,5.883730,1.570188e-02,True,OK
51,SGDPHP_RET,hybrid_arima_svr,test,0.301945,0.940475,3.327138e-01,False,OK
48,SGDPHP_RET,baseline_mean,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
49,SGDPHP_RET,baseline_rw,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
73,USDPHP_RET,var,test,0.150574,55.440285,5.513307e-13,True,OK
74,USDPHP_RET,varx,test,0.216013,52.714518,1.884163e-12,True,OK
62,USDPHP_RET,baseline_ar1,test,0.126658,50.795517,4.497743e-12,True,OK
60,USDPHP_RET,arima,test,0.154718,47.912677,1.675166e-11,True,OK
61,USDPHP_RET,arimax,test,0.247828,46.405674,3.343782e-11,True,OK
69,USDPHP_RET,hybrid_var_mlp,test,0.254148,20.431800,8.046716e-06,True,OK
71,USDPHP_RET,hybrid_varx_mlp,test,0.324862,16.556882,5.640722e-05,True,OK
67,USDPHP_RET,hybrid_arimax_mlp,test,0.345629,10.328878,1.410665e-03,True,OK
70,USDPHP_RET,hybrid_var_svr,test,0.262579,8.491234,3.759331e-03,True,OK
65,USDPHP_RET,hybrid_arima_mlp,test,0.269408,7.770239,5.552484e-03,True,OK
72,USDPHP_RET,hybrid_varx_svr,test,0.332508,7.238379,7.420779e-03,True,OK
68,USDPHP_RET,hybrid_arimax_svr,test,0.363941,2.611267,1.068578e-01,False,OK
66,USDPHP_RET,hybrid_arima_svr,test,0.280014,2.062106,1.517458e-01,False,OK
63,USDPHP_RET,baseline_mean,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."
64,USDPHP_RET,baseline_rw,test,NaN,NaN,NaN,False,"Skipped: forecast is constant, RESET not defined."

,Pair,Model,RESET_pvalue_val,RESET_pvalue_test,stable_conclusion
0,CNYPHP_RET,arima,0.002278,6.567532e-10,True
1,CNYPHP_RET,arimax,0.002494,3.998417e-11,True
2,CNYPHP_RET,baseline_ar1,0.005007,1.130262e-10,True
3,CNYPHP_RET,baseline_mean,NaN,NaN,True
4,CNYPHP_RET,baseline_rw,NaN,NaN,True
5,CNYPHP_RET,hybrid_arima_mlp,0.000002,3.762875e-02,True
6,CNYPHP_RET,hybrid_arima_svr,0.000005,7.139883e-01,False
7,CNYPHP_RET,hybrid_arimax_mlp,0.000015,5.940860e-02,False
8,CNYPHP_RET,hybrid_arimax_svr,0.000016,5.297155e-01,False
9,CNYPHP_RET,hybrid_var_mlp,0.663689,5.450566e-06,False
10,CNYPHP_RET,hybrid_var_svr,0.193822,1.537193e-03,False
11,CNYPHP_RET,hybrid_varx_mlp,0.764128,2.522287e-05,False
12,CNYPHP_RET,hybrid_varx_svr,0.753877,6.411716e-02,True
13,CNYPHP_RET,var,0.085386,5.604828e-13,False
14,CNYPHP_RET,varx,0.036248,7.494021e-14,True
15,HKDPHP_RET,arima,0.418487,1.531152e-11,False
16,HKDPHP_RET,arimax,0.533256,3.747028e-11,False
17,HKDPHP_RET,baseline_ar1,0.121009,5.589486e-12,False
18,HKDPHP_RET,baseline_mean,NaN,NaN,True
19,HKDPHP_RET,baseline_rw,NaN,NaN,True
20,HKDPHP_RET,hybrid_arima_mlp,0.568645,4.100989e-03,False
21,HKDPHP_RET,hybrid_arima_svr,0.654912,5.358939e-02,True
22,HKDPHP_RET,hybrid_arimax_mlp,0.052687,1.617263e-03,False
23,HKDPHP_RET,hybrid_arimax_svr,0.265538,7.600291e-02,True
24,HKDPHP_RET,hybrid_var_mlp,0.294622,1.530119e-06,False
25,HKDPHP_RET,hybrid_var_svr,0.897809,3.073597e-03,False
26,HKDPHP_RET,hybrid_varx_mlp,0.986530,5.165986e-05,False
27,HKDPHP_RET,hybrid_varx_svr,0.489690,2.519791e-02,False
28,HKDPHP_RET,var,0.029585,1.569226e-12,True
29,HKDPHP_RET,varx,0.071317,3.632553e-12,False
30,JPYPHP_RET,arima,0.186051,6.423771e-05,False
31,JPYPHP_RET,arimax,0.104504,6.239860e-01,True
32,JPYPHP_RET,baseline_ar1,0.167660,1.828262e-05,False
33,JPYPHP_RET,baseline_mean,NaN,NaN,True
34,JPYPHP_RET,baseline_rw,NaN,NaN,True
35,JPYPHP_RET,hybrid_arima_mlp,0.029964,3.752217e-02,True
36,JPYPHP_RET,hybrid_arima_svr,0.325052,3.630470e-01,True
37,JPYPHP_RET,hybrid_arimax_mlp,0.011368,2.957971e-01,False
38,JPYPHP_RET,hybrid_arimax_svr,0.053743,1.255393e-01,True
39,JPYPHP_RET,hybrid_var_mlp,0.239918,1.910397e-06,False
40,JPYPHP_RET,hybrid_var_svr,0.723069,2.355329e-03,False
41,JPYPHP_RET,hybrid_varx_mlp,0.287721,2.288753e-02,False
42,JPYPHP_RET,hybrid_varx_svr,0.234290,3.131989e-03,False
43,JPYPHP_RET,var,0.696450,1.729615e-05,False
44,JPYPHP_RET,varx,0.427424,9.772277e-02,True
45,SGDPHP_RET,arima,0.004225,4.556616e-12,True
46,SGDPHP_RET,arimax,0.101560,1.658329e-11,False
47,SGDPHP_RET,baseline_ar1,0.000662,8.590131e-14,True
48,SGDPHP_RET,baseline_mean,NaN,NaN,True
49,SGDPHP_RET,baseline_rw,NaN,NaN,True
50,SGDPHP_RET,hybrid_arima_mlp,0.020727,1.359068e-03,True
51,SGDPHP_RET,hybrid_arima_svr,0.024199,3.327138e-01,False
52,SGDPHP_RET,hybrid_arimax_mlp,0.062252,1.083926e-04,False
53,SGDPHP_RET,hybrid_arimax_svr,0.018965,1.570188e-02,True
54,SGDPHP_RET,hybrid_var_mlp,0.012569,1.399227e-08,True
55,SGDPHP_RET,hybrid_var_svr,0.000048,2.270338e-06,True
56,SGDPHP_RET,hybrid_varx_mlp,0.286028,1.173912e-08,False
57,SGDPHP_RET,hybrid_varx_svr,0.000150,5.529613e-06,True
58,SGDPHP_RET,var,0.146026,3.633838e-12,False
59,SGDPHP_RET,varx,0.731762,1.721270e-11,False
60,USDPHP_RET,arima,0.408211,1.675166e-11,False
61,USDPHP_RET,arimax,0.751417,3.343782e-11,False
62,USDPHP_RET,baseline_ar1,0.102622,4.497743e-12,False
63,USDPHP_RET,baseline_mean,NaN,NaN,True
64,USDPHP_RET,baseline_rw,NaN,NaN,True
65,USDPHP_RET,hybrid_arima_mlp,0.622347,5.552484e-03,False
66,USDPHP_RET,hybrid_arima_svr,0.784698,1.517458e-01,True
67,USDPHP_RET,hybrid_arimax_mlp,0.034436,1.410665e-03,True
68,USDPHP_RET,hybrid_arimax_svr,0.073775,1.068578e-01,True
69,USDPHP_RET,hybrid_var_mlp,0.239386,8.046716e-06,False
70,USDPHP_RET,hybrid_var_svr,0.279094,3.759331e-03,False
71,USDPHP_RET,hybrid_varx_mlp,0.925980,5.640722e-05,False
72,USDPHP_RET,hybrid_varx_svr,0.412702,7.420779e-03,False
73,USDPHP_RET,var,0.013207,5.513307e-13,True
74,USDPHP_RET,varx,0.064125,1.884163e-12,False

#### Interpretation
RESET results test functional-form adequacy. Rejection implies potential misspecification and motivates flexible nonlinear components; non-rejection supports the baseline functional form.

## 2) Validation vs Test Error Stability

A robust model should not deteriorate sharply when moving from validation to test.

In [16]:
stability_rows = []
for (pair, model), chunk in forecasts.groupby(['Pair', 'Model']):
    val_abs = chunk.loc[chunk['Set'] == 'val', 'AE'].dropna().values
    test_abs = chunk.loc[chunk['Set'] == 'test', 'AE'].dropna().values
    if len(val_abs) < 10 or len(test_abs) < 10:
        continue

    mw = stats.mannwhitneyu(val_abs, test_abs, alternative='two-sided')
    stability_rows.append({
        'Pair': pair,
        'Model': model,
        'Val_MAE': float(np.mean(val_abs)),
        'Test_MAE': float(np.mean(test_abs)),
        'Delta_Test_minus_Val': float(np.mean(test_abs) - np.mean(val_abs)),
        'MW_pvalue': float(mw.pvalue),
        'Distribution_shift_5pct': float(mw.pvalue) < 0.05,
    })

stability_df = pd.DataFrame(stability_rows).sort_values(['Pair', 'Delta_Test_minus_Val'])
display(stability_df)

,Pair,Model,Val_MAE,Test_MAE,Delta_Test_minus_Val,MW_pvalue,Distribution_shift_5pct
12,CNYPHP_RET,hybrid_varx_svr,0.418450,0.375845,-0.042606,0.251288,False
11,CNYPHP_RET,hybrid_varx_mlp,0.406809,0.374367,-0.032442,0.316465,False
10,CNYPHP_RET,hybrid_var_svr,0.425791,0.393824,-0.031967,0.476342,False
8,CNYPHP_RET,hybrid_arimax_svr,0.401076,0.369996,-0.031080,0.236601,False
7,CNYPHP_RET,hybrid_arimax_mlp,0.392226,0.365362,-0.026865,0.181261,False
6,CNYPHP_RET,hybrid_arima_svr,0.407449,0.382081,-0.025368,0.312135,False
9,CNYPHP_RET,hybrid_var_mlp,0.409594,0.387458,-0.022135,0.573202,False
14,CNYPHP_RET,varx,0.402555,0.383369,-0.019186,0.505379,False
5,CNYPHP_RET,hybrid_arima_mlp,0.396912,0.377803,-0.019109,0.291328,False
13,CNYPHP_RET,var,0.404971,0.394842,-0.010129,0.790956,False
1,CNYPHP_RET,arimax,0.387795,0.379623,-0.008172,0.528490,False
3,CNYPHP_RET,baseline_mean,0.404679,0.400646,-0.004033,0.334038,False
4,CNYPHP_RET,baseline_rw,0.404617,0.400792,-0.003825,0.348599,False
0,CNYPHP_RET,arima,0.392797,0.389092,-0.003705,0.551186,False
2,CNYPHP_RET,baseline_ar1,0.396941,0.395346,-0.001595,0.571670,False
26,HKDPHP_RET,hybrid_varx_mlp,0.289419,0.358320,0.068901,0.011144,True
27,HKDPHP_RET,hybrid_varx_svr,0.286405,0.355914,0.069509,0.011261,True
23,HKDPHP_RET,hybrid_arimax_svr,0.278182,0.350073,0.071890,0.002487,True
22,HKDPHP_RET,hybrid_arimax_mlp,0.278634,0.352410,0.073776,0.002593,True
25,HKDPHP_RET,hybrid_var_svr,0.301915,0.376444,0.074529,0.004180,True
24,HKDPHP_RET,hybrid_var_mlp,0.303378,0.381051,0.077673,0.003355,True
21,HKDPHP_RET,hybrid_arima_svr,0.293893,0.372183,0.078290,0.001406,True
29,HKDPHP_RET,varx,0.288541,0.370896,0.082355,0.010852,True
20,HKDPHP_RET,hybrid_arima_mlp,0.293237,0.376133,0.082895,0.000842,True
16,HKDPHP_RET,arimax,0.281817,0.366797,0.084980,0.004073,True
28,HKDPHP_RET,var,0.300915,0.392364,0.091450,0.001951,True
15,HKDPHP_RET,arima,0.292584,0.389792,0.097208,0.000818,True
17,HKDPHP_RET,baseline_ar1,0.294194,0.394605,0.100411,0.000395,True
19,HKDPHP_RET,baseline_rw,0.288736,0.404364,0.115627,0.000240,True
18,HKDPHP_RET,baseline_mean,0.288712,0.404515,0.115803,0.000216,True
41,JPYPHP_RET,hybrid_varx_mlp,0.493324,0.535938,0.042614,0.159944,False
42,JPYPHP_RET,hybrid_varx_svr,0.491454,0.535730,0.044277,0.111678,False
44,JPYPHP_RET,varx,0.494088,0.545987,0.051899,0.079544,False
38,JPYPHP_RET,hybrid_arimax_svr,0.471010,0.532580,0.061570,0.026561,True
40,JPYPHP_RET,hybrid_var_svr,0.513995,0.575611,0.061616,0.030365,True
39,JPYPHP_RET,hybrid_var_mlp,0.512713,0.574655,0.061942,0.033162,True
37,JPYPHP_RET,hybrid_arimax_mlp,0.472523,0.535440,0.062916,0.024271,True
43,JPYPHP_RET,var,0.512885,0.579212,0.066327,0.034078,True
31,JPYPHP_RET,arimax,0.472929,0.540326,0.067397,0.024611,True
32,JPYPHP_RET,baseline_ar1,0.491420,0.575157,0.083737,0.006420,True
36,JPYPHP_RET,hybrid_arima_svr,0.489409,0.573256,0.083847,0.003097,True
30,JPYPHP_RET,arima,0.490388,0.575145,0.084757,0.004431,True
35,JPYPHP_RET,hybrid_arima_mlp,0.488839,0.574074,0.085235,0.002221,True
34,JPYPHP_RET,baseline_rw,0.493434,0.589480,0.096045,0.005285,True
33,JPYPHP_RET,baseline_mean,0.493164,0.589515,0.096351,0.005064,True
56,SGDPHP_RET,hybrid_varx_mlp,0.294282,0.369077,0.074795,0.016535,True
57,SGDPHP_RET,hybrid_varx_svr,0.293921,0.370536,0.076615,0.012121,True
52,SGDPHP_RET,hybrid_arimax_mlp,0.271545,0.354480,0.082935,0.001826,True
54,SGDPHP_RET,hybrid_var_mlp,0.296854,0.380837,0.083983,0.002627,True
55,SGDPHP_RET,hybrid_var_svr,0.294861,0.381281,0.086420,0.001129,True
53,SGDPHP_RET,hybrid_arimax_svr,0.270873,0.357462,0.086589,0.001084,True
59,SGDPHP_RET,varx,0.295629,0.384446,0.088817,0.003745,True
51,SGDPHP_RET,hybrid_arima_svr,0.273726,0.366367,0.092642,0.000048,True
50,SGDPHP_RET,hybrid_arima_mlp,0.274925,0.367648,0.092723,0.000132,True
58,SGDPHP_RET,var,0.298424,0.395328,0.096904,0.000434,True
46,SGDPHP_RET,arimax,0.274311,0.371339,0.097028,0.000155,True
45,SGDPHP_RET,arima,0.280240,0.381385,0.101145,0.000073,True
47,SGDPHP_RET,baseline_ar1,0.284289,0.388872,0.104583,0.000068,True
48,SGDPHP_RET,baseline_mean,0.281529,0.401735,0.120206,0.000087,True
49,SGDPHP_RET,baseline_rw,0.281183,0.402016,0.120833,0.000068,True
71,USDPHP_RET,hybrid_varx_mlp,0.291199,0.358209,0.067010,0.009782,True
72,USDPHP_RET,hybrid_varx_svr,0.287912,0.356600,0.068688,0.009726,True
68,USDPHP_RET,hybrid_arimax_svr,0.279773,0.349938,0.070164,0.003826,True
67,USDPHP_RET,hybrid_arimax_mlp,0.282485,0.352732,0.070247,0.007277,True
70,USDPHP_RET,hybrid_var_svr,0.308037,0.378315,0.070278,0.016907,True
69,USDPHP_RET,hybrid_var_mlp,0.308853,0.381131,0.072278,0.010507,True
66,USDPHP_RET,hybrid_arima_svr,0.300359,0.373064,0.072706,0.007083,True
65,USDPHP_RET,hybrid_arima_mlp,0.299748,0.377275,0.077527,0.004747,True
74,USDPHP_RET,varx,0.290449,0.370272,0.079823,0.010800,True
61,USDPHP_RET,arimax,0.283947,0.365612,0.081665,0.006693,True
73,USDPHP_RET,var,0.306049,0.392106,0.086056,0.006151,True
60,USDPHP_RET,arima,0.298060,0.389484,0.091424,0.004150,True
62,USDPHP_RET,baseline_ar1,0.300231,0.394150,0.093920,0.002813,True
64,USDPHP_RET,baseline_rw,0.293773,0.404284,0.110511,0.000958,True
63,USDPHP_RET,baseline_mean,0.293534,0.404371,0.110838,0.000823,True

#### Interpretation
Validation-versus-test stability compares model behavior across splits. Small drift in metrics indicates robust generalization; large drift suggests overfitting or regime sensitivity.

## 3) Tail-Event Exclusion Sensitivity (DM)

We remove the top 1% absolute forecast errors by pair/model and re-run DM tests to verify conclusions are not driven only by a few extreme events.

In [17]:
trimmed = forecasts.copy()
trimmed['keep'] = True

for (pair, model), chunk in trimmed.groupby(['Pair', 'Model']):
    q = chunk['AE'].quantile(0.99)
    idx = chunk[chunk['AE'] > q].index
    trimmed.loc[idx, 'keep'] = False

trimmed = trimmed[trimmed['keep']].drop(columns=['keep'])

models = sorted(trimmed['Model'].unique().tolist())
dm_pairs = build_default_dm_pairs(models)

full_dm = run_dm_comparisons(forecasts, dm_pairs, criterion='mse', set_name='test')
trim_dm = run_dm_comparisons(trimmed, dm_pairs, criterion='mse', set_name='test')

merged_dm = full_dm.merge(
    trim_dm,
    on=['Pair', 'Model_A', 'Model_B', 'Loss', 'Set'],
    suffixes=('_full', '_trim')
)
merged_dm['same_significance'] = (
    (merged_dm['p_value_full'] < 0.05) == (merged_dm['p_value_trim'] < 0.05)
)
display(merged_dm.sort_values(['Pair', 'p_value_trim']))

,Pair,Model_A,Model_B,Loss,Set,DM_stat_full,p_value_full,n_obs_full,A_better_than_B_5pct_full,DM_stat_trim,p_value_trim,n_obs_trim,A_better_than_B_5pct_trim,same_significance
7,CNYPHP_RET,arimax,baseline_ar1,mse,test,-4.360069,1.635611e-05,423,True,-3.688673,2.554173e-04,416,True,True
8,CNYPHP_RET,arimax,baseline_mean,mse,test,-3.213419,1.412277e-03,423,True,-3.474125,5.663300e-04,417,True,True
9,CNYPHP_RET,arimax,baseline_rw,mse,test,-3.199968,1.478209e-03,423,True,-3.469661,5.755545e-04,417,True,True
16,CNYPHP_RET,hybrid_arimax_mlp,baseline_ar1,mse,test,-2.418999,1.598536e-02,423,True,-3.238139,1.299791e-03,416,True,True
17,CNYPHP_RET,hybrid_arimax_mlp,baseline_mean,mse,test,-2.457297,1.440006e-02,423,True,-2.908358,3.828463e-03,416,True,True
18,CNYPHP_RET,hybrid_arimax_mlp,baseline_rw,mse,test,-2.453043,1.456901e-02,423,True,-2.906121,3.855389e-03,416,True,True
38,CNYPHP_RET,varx,baseline_mean,mse,test,-2.711602,6.969376e-03,423,True,-2.403519,1.667486e-02,417,True,True
39,CNYPHP_RET,varx,baseline_rw,mse,test,-2.701946,7.171426e-03,423,True,-2.402327,1.672856e-02,417,True,True
4,CNYPHP_RET,arima,baseline_ar1,mse,test,-2.916155,3.732740e-03,423,True,-2.320902,2.077594e-02,416,True,True
6,CNYPHP_RET,arima,baseline_rw,mse,test,-2.587261,1.000769e-02,423,True,-2.293753,2.230364e-02,416,True,True
5,CNYPHP_RET,arima,baseline_mean,mse,test,-2.597348,9.723036e-03,423,True,-2.290644,2.248465e-02,416,True,True
30,CNYPHP_RET,hybrid_varx_mlp,baseline_rw,mse,test,-2.253587,2.473471e-02,423,True,-2.238181,2.573894e-02,416,True,True
29,CNYPHP_RET,hybrid_varx_mlp,baseline_mean,mse,test,-2.257338,2.449748e-02,423,True,-2.237104,2.580981e-02,416,True,True
28,CNYPHP_RET,hybrid_varx_mlp,baseline_ar1,mse,test,-2.118399,3.472515e-02,423,True,-2.142295,3.275108e-02,416,True,True
12,CNYPHP_RET,hybrid_arima_mlp,baseline_rw,mse,test,-2.118611,3.470713e-02,423,True,-2.091072,3.712925e-02,416,True,True
11,CNYPHP_RET,hybrid_arima_mlp,baseline_mean,mse,test,-2.121856,3.443196e-02,423,True,-2.089852,3.723930e-02,416,True,True
37,CNYPHP_RET,varx,baseline_ar1,mse,test,-2.744592,6.317208e-03,423,True,-2.028882,4.310818e-02,416,True,True
21,CNYPHP_RET,hybrid_arimax_svr,baseline_rw,mse,test,-2.140771,3.286489e-02,423,True,-1.970603,4.943360e-02,416,True,True
20,CNYPHP_RET,hybrid_arimax_svr,baseline_mean,mse,test,-2.143521,3.264231e-02,423,True,-1.966497,4.990721e-02,416,True,True
10,CNYPHP_RET,hybrid_arima_mlp,baseline_ar1,mse,test,-1.889760,5.947522e-02,423,False,-1.873852,6.165335e-02,416,False,True
33,CNYPHP_RET,hybrid_varx_svr,baseline_rw,mse,test,-2.005656,4.553085e-02,423,True,-1.699314,9.000945e-02,416,False,False
32,CNYPHP_RET,hybrid_varx_svr,baseline_mean,mse,test,-2.007999,4.528022e-02,423,True,-1.694351,9.094885e-02,416,False,False
36,CNYPHP_RET,var,baseline_rw,mse,test,-2.187641,2.924371e-02,423,True,-1.602262,1.098567e-01,417,False,False
35,CNYPHP_RET,var,baseline_mean,mse,test,-2.194668,2.873164e-02,423,True,-1.599813,1.103993e-01,417,False,False
15,CNYPHP_RET,hybrid_arima_svr,baseline_rw,mse,test,-1.622145,1.055192e-01,423,False,-1.581081,1.146212e-01,416,False,True
14,CNYPHP_RET,hybrid_arima_svr,baseline_mean,mse,test,-1.623035,1.053287e-01,423,False,-1.578820,1.151392e-01,416,False,True
24,CNYPHP_RET,hybrid_var_mlp,baseline_rw,mse,test,-1.940222,5.301853e-02,423,False,-1.513751,1.308503e-01,416,False,True
23,CNYPHP_RET,hybrid_var_mlp,baseline_mean,mse,test,-1.942979,5.268341e-02,423,False,-1.509186,1.320121e-01,416,False,True
19,CNYPHP_RET,hybrid_arimax_svr,baseline_ar1,mse,test,-1.886667,5.989143e-02,423,False,-1.334381,1.828107e-01,416,False,True
3,CNYPHP_RET,hybrid_var_mlp,var,mse,test,-1.521235,1.289497e-01,423,False,-1.285634,1.992861e-01,417,False,True
1,CNYPHP_RET,hybrid_arima_mlp,arima,mse,test,-1.619350,1.061191e-01,423,False,-1.204518,2.290760e-01,416,False,True
31,CNYPHP_RET,hybrid_varx_svr,baseline_ar1,mse,test,-1.710989,8.781795e-02,423,False,-1.067395,2.864141e-01,416,False,True
2,CNYPHP_RET,hybrid_var_svr,var,mse,test,-0.730174,4.656887e-01,423,False,0.977086,3.290945e-01,417,False,True
22,CNYPHP_RET,hybrid_var_mlp,baseline_ar1,mse,test,-1.609684,1.082146e-01,423,False,-0.869394,3.851341e-01,416,False,True
25,CNYPHP_RET,hybrid_var_svr,baseline_ar1,mse,test,-0.909281,3.637209e-01,423,False,0.677278,4.986068e-01,416,False,True
13,CNYPHP_RET,hybrid_arima_svr,baseline_ar1,mse,test,-1.142250,2.539977e-01,423,False,-0.603508,5.465013e-01,415,False,True
27,CNYPHP_RET,hybrid_var_svr,baseline_rw,mse,test,-1.481595,1.391944e-01,423,False,-0.536713,5.917534e-01,416,False,True
26,CNYPHP_RET,hybrid_var_svr,baseline_mean,mse,test,-1.482378,1.389862e-01,423,False,-0.527135,5.983815e-01,416,False,True
34,CNYPHP_RET,var,baseline_ar1,mse,test,-1.314347,1.894435e-01,423,False,-0.314024,7.536608e-01,416,False,True
0,CNYPHP_RET,hybrid_arima_svr,arima,mse,test,-0.920448,3.578645e-01,423,False,-0.118234,9.059393e-01,415,False,True
47,HKDPHP_RET,arimax,baseline_ar1,mse,test,-4.937314,1.142886e-06,423,True,-5.440962,9.099055e-08,414,True,True
77,HKDPHP_RET,varx,baseline_ar1,mse,test,-4.172898,3.653773e-05,423,True,-4.205507,3.196599e-05,414,True,True
56,HKDPHP_RET,hybrid_arimax_mlp,baseline_ar1,mse,test,-3.049636,2.435533e-03,423,True,-4.006618,7.309110e-05,413,True,True
48,HKDPHP_RET,arimax,baseline_mean,mse,test,-3.631001,3.170168e-04,423,True,-3.977465,8.230756e-05,412,True,True
49,HKDPHP_RET,arimax,baseline_rw,mse,test,-3.608311,3.451494e-04,423,True,-3.967544,8.567639e-05,412,True,True
68,HKDPHP_RET,hybrid_varx_mlp,baseline_ar1,mse,test,-3.048111,2.447652e-03,423,True,-3.563865,4.082272e-04,413,True,True
57,HKDPHP_RET,hybrid_arimax_mlp,baseline_mean,mse,test,-2.850683,4.576501e-03,423,True,-3.505100,5.067856e-04,411,True,True
60,HKDPHP_RET,hybrid_arimax_svr,baseline_mean,mse,test,-2.718757,6.822988e-03,423,True,-3.500321,5.156879e-04,411,True,True
58,HKDPHP_RET,hybrid_arimax_mlp,baseline_rw,mse,test,-2.840719,4.719124e-03,423,True,-3.496323,5.232479e-04,411,True,True
61,HKDPHP_RET,hybrid_arimax_svr,baseline_rw,mse,test,-2.710376,6.994746e-03,423,True,-3.490878,5.337109e-04,411,True,True
59,HKDPHP_RET,hybrid_arimax_svr,baseline_ar1,mse,test,-2.787944,5.544113e-03,423,True,-3.406835,7.218227e-04,413,True,True
78,HKDPHP_RET,varx,baseline_mean,mse,test,-3.493210,5.276820e-04,423,True,-3.396328,7.493162e-04,413,True,True
79,HKDPHP_RET,varx,baseline_rw,mse,test,-3.470908,5.721678e-04,423,True,-3.390868,7.639881e-04,413,True,True
69,HKDPHP_RET,hybrid_varx_mlp,baseline_mean,mse,test,-2.835330,4.797943e-03,423,True,-3.141489,1.802522e-03,412,True,True
70,HKDPHP_RET,hybrid_varx_mlp,baseline_rw,mse,test,-2.825314,4.947595e-03,423,True,-3.137168,1.828663e-03,412,True,True
71,HKDPHP_RET,hybrid_varx_svr,baseline_ar1,mse,test,-2.492958,1.305070e-02,423,True,-2.373135,1.809693e-02,412,True,True
50,HKDPHP_RET,hybrid_arima_mlp,baseline_ar1,mse,test,-2.173391,3.030637e-02,423,True,-2.249421,2.501306e-02,413,True,True
73,HKDPHP_RET,hybrid_varx_svr,baseline_rw,mse,test,-2.531819,1.170913e-02,423,True,-2.073977,3.870669e-02,410,True,True
72,HKDPHP_RET,hybrid_varx_svr,baseline_mean,mse,test,-2.539110,1.147157e-02,423,True,-2.073842,3.871927e-02,410,True,True
52,HKDPHP_RET,hybrid_arima_mlp,baseline_rw,mse,test,-2.309433,2.140163e-02,423,True,-1.860317,6.355653e-02,411,False,False
51,HKDPHP_RET,hybrid_arima_mlp,baseline_mean,mse,test,-2.317294,2.096543e-02,423,True,-1.858203,6.385671e-02,411,False,False
41,HKDPHP_RET,hybrid_arima_mlp,arima,mse,test,-1.956150,5.110677e-02,423,False,-1.803450,7.204804e-02,413,False,True
75,HKDPHP_RET,var,baseline_mean,mse,test,-2.595465,9.775611e-03,423,True,-1.628430,1.041982e-01,413,False,False
76,HKDPHP_RET,var,baseline_rw,mse,test,-2.578664,1.025611e-02,423,True,-1.626629,1.045805e-01,413,False,False
44,HKDPHP_RET,arima,baseline_ar1,mse,test,-2.502221,1.271910e-02,423,True,-1.616646,1.067164e-01,415,False,False
53,HKDPHP_RET,hybrid_arima_svr,baseline_ar1,mse,test,-2.032688,4.270965e-02,423,True,-1.606899,1.088427e-01,413,False,False
62,HKDPHP_RET,hybrid_var_mlp,baseline_ar1,mse,test,-2.145032,3.252050e-02,423,True,-1.605142,1.092287e-01,413,False,False
45,HKDPHP_RET,arima,baseline_mean,mse,test,-2.612466,9.310010e-03,423,True,-1.563046,1.188094e-01,413,False,False
46,HKDPHP_RET,arima,baseline_rw,mse,test,-2.594790,9.794521e-03,423,True,-1.557637,1.200871e-01,413,False,False
43,HKDPHP_RET,hybrid_var_mlp,var,mse,test,-1.883808,6.027824e-02,423,False,-1.553116,1.211613e-01,414,False,True
64,HKDPHP_RET,hybrid_var_mlp,baseline_rw,mse,test,-2.295077,2.221862e-02,423,True,-1.455882,1.461886e-01,412,False,False
63,HKDPHP_RET,hybrid_var_mlp,baseline_mean,mse,test,-2.302987,2.176514e-02,423,True,-1.454681,1.465208e-01,412,False,False
54,HKDPHP_RET,hybrid_arima_svr,baseline_mean,mse,test,-2.233067,2.606816e-02,423,True,-1.429532,1.536129e-01,411,False,False
55,HKDPHP_RET,hybrid_arima_svr,baseline_rw,mse,test,-2.226339,2.651875e-02,423,True,-1.426401,1.545136e-01,411,False,False
40,HKDPHP_RET,hybrid_arima_svr,arima,mse,test,-1.853139,6.456021e-02,423,False,-1.245403,2.136915e-01,413,False,True
65,HKDPHP_RET,hybrid_var_svr,baseline_ar1,mse,test,-1.924151,5.500781e-02,423,False,-1.148156,2.515722e-01,412,False,True
74,HKDPHP_RET,var,baseline_ar1,mse,test,-1.836843,6.693615e-02,423,False,-1.045523,2.963928e-01,414,False,True
42,HKDPHP_RET,hybrid_var_svr,var,mse,test,-1.708765,8.822972e-02,423,False,-0.947346,3.440191e-01,412,False,True
67,HKDPHP_RET,hybrid_var_svr,baseline_rw,mse,test,-2.161576,3.121255e-02,423,True,-0.697639,4.857997e-01,410,False,False
66,HKDPHP_RET,hybrid_var_svr,baseline_mean,mse,test,-2.168060,3.071237e-02,423,True,-0.693623,4.883125e-01,410,False,False
97,JPYPHP_RET,hybrid_arimax_mlp,baseline_mean,mse,test,-4.523562,7.914514e-06,423,True,-4.490437,9.240469e-06,413,True,True
98,JPYPHP_RET,hybrid_arimax_mlp,baseline_rw,mse,test,-4.536246,7.474189e-06,423,True,-4.485482,9.447571e-06,413,True,True
100,JPYPHP_RET,hybrid_arimax_svr,baseline_mean,mse,test,-4.109751,4.760281e-05,423,True,-4.277255,2.354392e-05,413,True,True
101,JPYPHP_RET,hybrid_arimax_svr,baseline_rw,mse,test,-4.123547,4.494230e-05,423,True,-4.275512,2.372092e-05,413,True,True
88,JPYPHP_RET,arimax,baseline_mean,mse,test,-4.239269,2.756879e-05,423,True,-4.257609,2.561454e-05,413,True,True
89,JPYPHP_RET,arimax,baseline_rw,mse,test,-4.248698,2.647954e-05,423,True,-4.254190,2.599218e-05,413,True,True
86,JPYPHP_RET,arima,baseline_rw,mse,test,-3.953384,9.033555e-05,423,True,-3.662888,2.817413e-04,415,True,True
85,JPYPHP_RET,arima,baseline_mean,mse,test,-3.904925,1.097140e-04,423,True,-3.634085,3.140545e-04,415,True,True
92,JPYPHP_RET,hybrid_arima_mlp,baseline_rw,mse,test,-3.660186,2.839927e-04,423,True,-3.477877,5.589497e-04,415,True,True
91,JPYPHP_RET,hybrid_arima_mlp,baseline_mean,mse,test,-3.626748,3.221201e-04,423,True,-3.453332,6.107852e-04,415,True,True
96,JPYPHP_RET,hybrid_arimax_mlp,baseline_ar1,mse,test,-3.724037,2.226795e-04,423,True,-3.452139,6.137030e-04,413,True,True
99,JPYPHP_RET,hybrid_arimax_svr,baseline_ar1,mse,test,-3.559262,4.141661e-04,423,True,-3.248224,1.256395e-03,413,True,True
110,JPYPHP_RET,hybrid_varx_mlp,baseline_rw,mse,test,-3.720909,2.253672e-04,423,True,-3.244950,1.270562e-03,413,True,True
109,JPYPHP_RET,hybrid_varx_mlp,baseline_mean,mse,test,-3.709745,2.352093e-04,423,True,-3.241004,1.287832e-03,413,True,True
119,JPYPHP_RET,varx,baseline_rw,mse,test,-3.599443,3.567692e-04,423,True,-3.063334,2.332544e-03,413,True,True
118,JPYPHP_RET,varx,baseline_mean,mse,test,-3.589117,3.707615e-04,423,True,-3.059620,2.361003e-03,413,True,True
113,JPYPHP_RET,hybrid_varx_svr,baseline_rw,mse,test,-3.458998,5.973368e-04,423,True,-3.056205,2.387454e-03,413,True,True
112,JPYPHP_RET,hybrid_varx_svr,baseline_mean,mse,test,-3.448022,6.214455e-04,423,True,-3.050375,2.433232e-03,413,True,True
87,JPYPHP_RET,arimax,baseline_ar1,mse,test,-2.844862,4.659343e-03,423,True,-3.011317,2.761333e-03,413,True,True
108,JPYPHP_RET,hybrid_varx_mlp,baseline_ar1,mse,test,-3.123865,1.907995e-03,423,True,-2.346815,1.940743e-02,413,True,True
95,JPYPHP_RET,hybrid_arima_svr,baseline_rw,mse,test,-2.687430,7.485088e-03,423,True,-2.293858,2.229872e-02,415,True,True
94,JPYPHP_RET,hybrid_arima_svr,baseline_mean,mse,test,-2.670102,7.875665e-03,423,True,-2.276787,2.330854e-02,415,True,True
83,JPYPHP_RET,hybrid_var_mlp,var,mse,test,-2.574874,1.036739e-02,423,True,-2.101770,3.617421e-02,417,True,True
111,JPYPHP_RET,hybrid_varx_svr,baseline_ar1,mse,test,-2.925629,3.623158e-03,423,True,-2.097461,3.656160e-02,413,True,True
117,JPYPHP_RET,varx,baseline_ar1,mse,test,-2.676009,7.740520e-03,423,True,-1.988229,4.744763e-02,413,True,True
104,JPYPHP_RET,hybrid_var_mlp,baseline_rw,mse,test,-2.163428,3.106896e-02,423,True,-1.481197,1.393149e-01,415,False,False
103,JPYPHP_RET,hybrid_var_mlp,baseline_mean,mse,test,-2.151837,3.197689e-02,423,True,-1.473495,1.413774e-01,415,False,False
116,JPYPHP_RET,var,baseline_rw,mse,test,-1.934249,5.375075e-02,423,False,-1.315182,1.891768e-01,415,False,True
115,JPYPHP_RET,var,baseline_mean,mse,test,-1.922821,5.517519e-02,423,False,-1.307800,1.916670e-01,415,False,True
90,JPYPHP_RET,hybrid_arima_mlp,baseline_ar1,mse,test,-2.453302,1.455865e-02,423,True,-1.266632,2.059991e-01,415,False,False
105,JPYPHP_RET,hybrid_var_svr,baseline_ar1,mse,test,-0.629996,5.290382e-01,423,False,1.125691,2.609485e-01,415,False,True
84,JPYPHP_RET,arima,baseline_ar1,mse,test,-1.152658,2.497032e-01,423,False,-1.067536,2.863518e-01,415,False,True
82,JPYPHP_RET,hybrid_var_svr,var,mse,test,-1.319300,1.877840e-01,423,False,-1.035179,3.011866e-01,417,False,True
80,JPYPHP_RET,hybrid_arima_svr,arima,mse,test,-1.138182,2.556904e-01,423,False,1.034063,3.017106e-01,415,False,True
81,JPYPHP_RET,hybrid_arima_mlp,arima,mse,test,-2.333771,2.007640e-02,423,True,-1.005608,3.151915e-01,415,False,False
107,JPYPHP_RET,hybrid_var_svr,baseline_rw,mse,test,-1.876059,6.133723e-02,423,False,-1.003808,3.160575e-01,415,False,True
106,JPYPHP_RET,hybrid_var_svr,baseline_mean,mse,test,-1.867358,6.254471e-02,423,False,-0.996656,3.195137e-01,415,False,True
114,JPYPHP_RET,var,baseline_ar1,mse,test,0.077586,9.381940e-01,423,False,0.868023,3.858844e-01,415,False,True
93,JPYPHP_RET,hybrid_arima_svr,baseline_ar1,mse,test,-1.216201,2.245883e-01,423,False,0.808904,4.190351e-01,415,False,True
102,JPYPHP_RET,hybrid_var_mlp,baseline_ar1,mse,test,-0.737318,4.613385e-01,423,False,0.385393,7.001440e-01,415,False,True
136,SGDPHP_RET,hybrid_arimax_mlp,baseline_ar1,mse,test,-2.956903,3.281934e-03,423,True,-3.691209,2.531140e-04,414,True,True
137,SGDPHP_RET,hybrid_arimax_mlp,baseline_mean,mse,test,-2.994704,2.908819e-03,423,True,-3.629867,3.191575e-04,414,True,True
138,SGDPHP_RET,hybrid_arimax_mlp,baseline_rw,mse,test,-2.982616,3.023679e-03,423,True,-3.624292,3.259021e-04,414,True,True
129,SGDPHP_RET,arimax,baseline_rw,mse,test,-3.261469,1.198331e-03,423,True,-3.520709,4.783362e-04,414,True,True
128,SGDPHP_RET,arimax,baseline_mean,mse,test,-3.279672,1.125445e-03,423,True,-3.514959,4.885029e-04,414,True,True
130,SGDPHP_RET,hybrid_arima_mlp,baseline_ar1,mse,test,-2.672356,7.823850e-03,423,True,-3.457887,6.009809e-04,414,True,True
126,SGDPHP_RET,arima,baseline_rw,mse,test,-3.202202,1.467065e-03,423,True,-3.281669,1.119618e-03,414,True,True
125,SGDPHP_RET,arima,baseline_mean,mse,test,-3.222217,1.370635e-03,423,True,-3.274236,1.148718e-03,414,True,True
131,SGDPHP_RET,hybrid_arima_mlp,baseline_mean,mse,test,-2.802993,5.296470e-03,423,True,-3.181117,1.577825e-03,414,True,True
132,SGDPHP_RET,hybrid_arima_mlp,baseline_rw,mse,test,-2.791654,5.482113e-03,423,True,-3.179495,1.586465e-03,414,True,True
134,SGDPHP_RET,hybrid_arima_svr,baseline_mean,mse,test,-2.603236,9.560266e-03,423,True,-3.160308,1.692071e-03,414,True,True
135,SGDPHP_RET,hybrid_arima_svr,baseline_rw,mse,test,-2.595014,9.788253e-03,423,True,-3.159785,1.695040e-03,414,True,True
124,SGDPHP_RET,arima,baseline_ar1,mse,test,-3.227722,1.345162e-03,423,True,-3.092229,2.121351e-03,414,True,True
141,SGDPHP_RET,hybrid_arimax_svr,baseline_rw,mse,test,-2.614928,9.244257e-03,423,True,-2.933245,3.541240e-03,414,True,True
140,SGDPHP_RET,hybrid_arimax_svr,baseline_mean,mse,test,-2.622968,9.032390e-03,423,True,-2.930558,3.571370e-03,414,True,True
133,SGDPHP_RET,hybrid_arima_svr,baseline_ar1,mse,test,-2.294502,2.225187e-02,423,True,-2.775709,5.758520e-03,414,True,True
123,SGDPHP_RET,hybrid_var_mlp,var,mse,test,-2.400855,1.678876e-02,423,True,-2.771400,5.833862e-03,414,True,True
150,SGDPHP_RET,hybrid_varx_mlp,baseline_rw,mse,test,-2.618955,9.137588e-03,423,True,-2.755782,6.114441e-03,414,True,True
149,SGDPHP_RET,hybrid_varx_mlp,baseline_mean,mse,test,-2.630072,8.848827e-03,423,True,-2.754372,6.140362e-03,414,True,True
154,SGDPHP_RET,var,baseline_ar1,mse,test,2.598851,9.681269e-03,423,False,2.692855,7.372653e-03,414,False,True
159,SGDPHP_RET,varx,baseline_rw,mse,test,-2.595104,9.785738e-03,423,True,-2.371754,1.816043e-02,415,True,True
158,SGDPHP_RET,varx,baseline_mean,mse,test,-2.611086,9.347047e-03,423,True,-2.367001,1.839207e-02,415,True,True
144,SGDPHP_RET,hybrid_var_mlp,baseline_rw,mse,test,-2.452475,1.459167e-02,423,True,-2.291197,2.245479e-02,414,True,True
143,SGDPHP_RET,hybrid_var_mlp,baseline_mean,mse,test,-2.462869,1.418138e-02,423,True,-2.285210,2.280666e-02,414,True,True
127,SGDPHP_RET,arimax,baseline_ar1,mse,test,-2.736879,6.464538e-03,423,True,-2.284799,2.283100e-02,414,True,True
148,SGDPHP_RET,hybrid_varx_mlp,baseline_ar1,mse,test,-2.208129,2.777229e-02,423,True,-2.110946,3.537739e-02,414,True,True
139,SGDPHP_RET,hybrid_arimax_svr,baseline_ar1,mse,test,-2.272665,2.354852e-02,423,True,-1.972674,4.919931e-02,414,True,True
156,SGDPHP_RET,var,baseline_rw,mse,test,-2.383911,1.757094e-02,423,True,-1.900185,5.810505e-02,414,False,False
155,SGDPHP_RET,var,baseline_mean,mse,test,-2.398208,1.690889e-02,423,True,-1.885732,6.003261e-02,414,False,False
153,SGDPHP_RET,hybrid_varx_svr,baseline_rw,mse,test,-2.227898,2.641373e-02,423,True,-1.850522,6.495395e-02,413,False,False
152,SGDPHP_RET,hybrid_varx_svr,baseline_mean,mse,test,-2.234070,2.600156e-02,423,True,-1.844100,6.588637e-02,413,False,False
121,SGDPHP_RET,hybrid_arima_mlp,arima,mse,test,-2.040242,4.194822e-02,423,True,-1.830859,6.784200e-02,414,False,False
147,SGDPHP_RET,hybrid_var_svr,baseline_rw,mse,test,-2.080865,3.804881e-02,423,True,-1.434216,1.522710e-01,412,False,False
146,SGDPHP_RET,hybrid_var_svr,baseline_mean,mse,test,-2.086427,3.753978e-02,423,True,-1.421788,1.558461e-01,412,False,False
120,SGDPHP_RET,hybrid_arima_svr,arima,mse,test,-1.852776,6.461237e-02,423,False,-1.320621,1.873590e-01,414,False,True
142,SGDPHP_RET,hybrid_var_mlp,baseline_ar1,mse,test,-1.839709,6.651312e-02,423,False,-0.993752,3.209256e-01,414,False,True
145,SGDPHP_RET,hybrid_var_svr,baseline_ar1,mse,test,-1.394761,1.638218e-01,423,False,0.477068,6.335674e-01,412,False,True
122,SGDPHP_RET,hybrid_var_svr,var,mse,test,-1.675925,9.449347e-02,423,False,-0.397731,6.910351e-01,412,False,True
151,SGDPHP_RET,hybrid_varx_svr,baseline_ar1,mse,test,-1.630541,1.037333e-01,423,False,-0.353128,7.241734e-01,413,False,True
157,SGDPHP_RET,varx,baseline_ar1,mse,test,-0.024020,9.808483e-01,423,False,0.020219,9.838781e-01,414,False,True
167,USDPHP_RET,arimax,baseline_ar1,mse,test,-5.007419,8.121293e-07,423,True,-5.473513,7.669602e-08,414,True,True
168,USDPHP_RET,arimax,baseline_mean,mse,test,-3.752073,1.999059e-04,423,True,-4.291851,2.211007e-05,413,True,True
169,USDPHP_RET,arimax,baseline_rw,mse,test,-3.728767,2.186733e-04,423,True,-4.282364,2.303216e-05,413,True,True
176,USDPHP_RET,hybrid_arimax_mlp,baseline_ar1,mse,test,-3.198233,1.486918e-03,423,True,-4.155336,3.950078e-05,414,True,True
197,USDPHP_RET,varx,baseline_ar1,mse,test,-4.203892,3.204930e-05,423,True,-4.129219,4.406481e-05,414,True,True
180,USDPHP_RET,hybrid_arimax_svr,baseline_mean,mse,test,-2.797195,5.390672e-03,423,True,-3.881322,1.210330e-04,411,True,True
181,USDPHP_RET,hybrid_arimax_svr,baseline_rw,mse,test,-2.788682,5.531736e-03,423,True,-3.870251,1.264591e-04,411,True,True

#### Interpretation
Tail-sensitivity DM analysis checks whether conclusions hold after trimming extremes. If significance patterns persist, relative model ranking is not driven only by outlier episodes.

In [18]:
out_dir = f'results/{active_target}/evaluation'
os.makedirs(out_dir, exist_ok=True)

reset_test.to_csv(f'{out_dir}/reset_test_results.csv', index=False)
stability_df.to_csv(f'{out_dir}/val_test_error_stability.csv', index=False)
merged_dm.to_csv(f'{out_dir}/dm_tail_sensitivity.csv', index=False)

print('Saved robustness outputs to', out_dir)

Saved robustness outputs to results/PHP/evaluation

#### Interpretation
This save step records robustness tables for reproducible reporting. Stored outputs should match the tables displayed above to ensure consistency.